-- MySQL Script generated by MySQL Workbench
-- Wed Aug  5 13:14:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema patrones_sql
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `patrones_sql` ;

-- -----------------------------------------------------
-- Schema patrones_sql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `patrones_sql` DEFAULT CHARACTER SET utf8 ;
USE `patrones_sql` ;

-- -----------------------------------------------------
-- Table `patrones_sql`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patrones_sql`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `patrones_sql`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `ct_descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `patrones_sql`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patrones_sql`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `patrones_sql`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `p_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `patrones_sql`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patrones_sql`.`Producto` ;

CREATE TABLE IF NOT EXISTS `patrones_sql`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `p_nombre` VARCHAR(45) NOT NULL,
  `p_marca` VARCHAR(45) NULL,
  `Categoria_idCategoria` INT NOT NULL,
  `Proveedor_idProveedor` INT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_Categoria1_idx` (`Categoria_idCategoria` ASC),
  INDEX `fk_Producto_Proveedor1_idx` (`Proveedor_idProveedor` ASC),
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `patrones_sql`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `patrones_sql`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `patrones_sql`.`Bodega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patrones_sql`.`Bodega` ;

CREATE TABLE IF NOT EXISTS `patrones_sql`.`Bodega` (
  `idBodega` INT NOT NULL AUTO_INCREMENT,
  `b_ubicacion` VARCHAR(45) NOT NULL,
  `b_capacidad` INT NOT NULL,
  PRIMARY KEY (`idBodega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `patrones_sql`.`Inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patrones_sql`.`Inventario` ;

CREATE TABLE IF NOT EXISTS `patrones_sql`.`Inventario` (
  `Bodega_idBodega` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `i_cantidad` INT NOT NULL,
  `i_fecha` DATE NOT NULL,
  `i_estado` TINYINT NOT NULL,
  PRIMARY KEY (`Bodega_idBodega`, `Producto_idProducto`),
  INDEX `fk_Producto_has_Bodega_Bodega1_idx` (`Bodega_idBodega` ASC),
  INDEX `fk_Inventario_Producto1_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Producto_has_Bodega_Bodega1`
    FOREIGN KEY (`Bodega_idBodega`)
    REFERENCES `patrones_sql`.`Bodega` (`idBodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `patrones_sql`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `patrones_sql`.`Tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patrones_sql`.`Tipo` ;

CREATE TABLE IF NOT EXISTS `patrones_sql`.`Tipo` (
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  `t_descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `patrones_sql`.`Cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patrones_sql`.`Cargo` ;

CREATE TABLE IF NOT EXISTS `patrones_sql`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `c_descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `patrones_sql`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patrones_sql`.`Persona` ;

CREATE TABLE IF NOT EXISTS `patrones_sql`.`Persona` (
  `idPersona` BIGINT(11) NOT NULL,
  `Cargo_idCargo` INT NOT NULL,
  `p_nombre` VARCHAR(45) NOT NULL,
  `p_celular` BIGINT(12) NULL,
  `idJefe` BIGINT(11) NULL,
  `Bodega_idBodega` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_Persona_Cargo1_idx` (`Cargo_idCargo` ASC),
  INDEX `fk_Persona_Bodega1_idx` (`Bodega_idBodega` ASC),
  INDEX `fk_Persona_Persona1_idx` (`idJefe` ASC),
  CONSTRAINT `fk_Persona_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `patrones_sql`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Bodega1`
    FOREIGN KEY (`Bodega_idBodega`)
    REFERENCES `patrones_sql`.`Bodega` (`idBodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_Persona1`
    FOREIGN KEY (`idJefe`)
    REFERENCES `patrones_sql`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `patrones_sql`.`Movimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `patrones_sql`.`Movimiento` ;

CREATE TABLE IF NOT EXISTS `patrones_sql`.`Movimiento` (
  `idMovimiento` INT NOT NULL,
  `Bodega_idBodega` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `Bodega_idBodegaDestino` INT NULL DEFAULT NULL,
  `Tipo_idTipo` INT NOT NULL,
  `m_fecha` DATETIME NOT NULL,
  `m_cantidad` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idMovimiento`, `Bodega_idBodega`, `Producto_idProducto`),
  INDEX `fk_Movimiento_Bodega1_idx` (`Bodega_idBodega` ASC),
  INDEX `fk_Movimiento_Bodega2_idx` (`Bodega_idBodegaDestino` ASC),
  INDEX `fk_Movimiento_Tipo1_idx` (`Tipo_idTipo` ASC),
  INDEX `fk_Movimiento_Producto1_idx` (`Producto_idProducto` ASC),
  INDEX `fk_Movimiento_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Movimiento_Bodega`
    FOREIGN KEY (`Bodega_idBodega`)
    REFERENCES `patrones_sql`.`Bodega` (`idBodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimiento_BodegaDestino`
    FOREIGN KEY (`Bodega_idBodegaDestino`)
    REFERENCES `patrones_sql`.`Bodega` (`idBodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimiento_Tipo1`
    FOREIGN KEY (`Tipo_idTipo`)
    REFERENCES `patrones_sql`.`Tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimiento_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `patrones_sql`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimiento_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `patrones_sql`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
